### PR TITLE
Fixes #72 incorrect lastTag calculation

### LINKED ISSUE #72: lastTag is incorrectly calculated
`getLastTags` in `src/main/groovy/net/nemerosa/versioning/git/GitInfoService.groovy` is returning the tags sorted in incorrect order.
The main criteria for sorting should be the tag commit time, and second criteria should be desc version, however it seems that the result of commit time based sort is ignored due to the chaining of calls to `sort()`
```groovy
    @Override
    List<String> getLastTags(Project project, VersioningExtension extension, String tagPattern) {
        def grgit = Grgit.open(currentDir: getGitDirectory(extension, project))
        return grgit.tag.list()
                .findAll { (it.name =~ tagPattern).find() }
                .sort { -it.commit.time }
                .sort { -TagSupport.tagOrder(tagPattern, it.name) } // <-- second sort, overriding the first
                .collect { it.name }
    }
```

Example problematic scenario : 
- you have an old commit tagged as '1.2.16'
- you have the most recent commit, tagged as '1.3.12'

`./gradlew versionDisplay` will return 

```
[version] display     = 1.3.13
[version] tag         =
[version] lastTag     = 1.2.16
```
because 16 is bigger than 13 and because the commit time of 1.3.13 is ignored.

I'm already working on a fix for this, and I have written test scenarios so you can assign this issue to me

### PR DESCRIPTION
**Pull request by MorganGeek**
sorting strategy described below:
- first we sort by commit time (desc)
- then we sort on the tag (last digits, desc)

### CODE REVIEW

File: src/main/groovy/net/nemerosa/versioning/git/GitInfoService.groovy [hunk 1]
```diff
@@ -21,9 +21,9 @@ class GitInfoService implements SCMInfoService {
     SCMInfo getInfo(Project project, VersioningExtension extension) {
         // Is Git enabled?
         boolean hasGit = project.rootProject.file('.git').exists() ||
-                project.file('.git').exists() ||
-                (extension.gitRepoRootDir != null &&
-                        new File(extension.gitRepoRootDir, '.git').exists())
+        project.file('.git').exists() ||
+        (extension.gitRepoRootDir != null &&
+        new File(extension.gitRepoRootDir, '.git').exists())
```
Comment (dcoraboeuf) [inline src/main/groovy/net/nemerosa/versioning/git/GitInfoService.groovy]: Cosmetic, but can you restore the initial indentation? I don't think this code has changed.

**Comment by MorganGeek** [comment]
Styling restored - review requested again ;-)
